typography_spectrum: 0.7222222
color:
  saturation: 0.8835126
  brandStrength: 0.5534726
  lightness: 0.1272401
  rhythmicContrast: 0.9802867
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.9910395
name: Lives I haven't lived
title: The River
description: Stories from the bottom of the Mediterranean Sea
